name: code-coverage
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: write
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: go-test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
      - name: go-coverage-badge  # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage.out
      - name: verify-changed
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: README.md
      - name: current-branch
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          set -x
          ref=$(git symbolic-ref --quiet HEAD 2> /dev/null)
          ret=$?
          if [[ $ret != 0 ]]
          then
            [[ $ret == 128 ]] && return
            ref=$(git rev-parse --short HEAD 2> /dev/null)  || return
          fi
          echo ${ref#refs/heads/}

      - name: commit-changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."
          git fetch origin && git rebase origin/master
          git push origin HEAD:${{ steps.current-branch.outputs.stdout }}
